# Pandas

In [10]:
# in pandas have three types
# 1. series 2.DataFrame 3. panel(combination series and DataFrame)

In [11]:
# how to create series
import pandas as pd
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [12]:
# how to create empty series
pd.Series(dtype="object")

Series([], dtype: object)

In [13]:
data = [10, 20, 30 ,40, 50]
pd.Series(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [14]:
# using numpy create a series
import numpy as np
pd.Series(np.arange(1,11))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [ ]:
# series is composed two things 
# 1. index(label) 2. values(data)

# Index in series

In [15]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
# if we pass the data in series they get index is by default
# but we want to get own indexing its possible, we can get our own indexing

In [16]:
a = pd.Series(np.arange(1, 7), index=np.arange(1,7))
a

1    1
2    2
3    3
4    4
5    5
6    6
dtype: int32

In [17]:
# if we want to get character in index
# but number of data/ values equal number of index must be match otherwise its will give error
a = pd.Series(np.arange(1, 7), index=["A", "B", "C", "D", "E", "F"])
a

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int32

In [24]:
a[5] # we will get the charater as index but we want access the data in series we need to int index but (dtype is int)

6

# dtype in series , how to change dtype

In [26]:
s1 = pd.Series([10,20, 30, 40, 50, 60])
s1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [31]:
s1 = pd.Series([10,20, 30, 40, 50, 60],dtype="int8") # change dtype int64 into int8
s1 

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int8

In [32]:
s2 = pd.Series([10,20, 30, 40, 50, 60], dtype="object") # object means string
s2

0    10
1    20
2    30
3    40
4    50
5    60
dtype: object

In [34]:
s3 = pd.Series(["a", 12, 34, 35.0, 3+4j]) # in this series dtype is object
s3

0       a
1      12
2      34
3    35.0
dtype: object

In [43]:
pd.Series([12, 34, 35.0, 3+4j], dtype="complex64") # its dtype is complex, by default is 'complex128'

0    12.0+0.0j
1    34.0+0.0j
2    35.0+0.0j
3     3.0+4.0j
dtype: complex64

In [44]:
pd.Series([12, 34, 35.0]) # dtype is float

0    12.0
1    34.0
2    35.0
dtype: float64

# Name

In [47]:
pd.Series(np.arange(1,6), name="a1")

0    1
1    2
2    3
3    4
4    5
Name: a1, dtype: int32

In [49]:
# fetch the values
s

0    1
1    2
2    3
3    4
dtype: int64

In [52]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [56]:
# i want get index
a

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int32

In [57]:
a.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [59]:
a.dtype

dtype('int32')

# Summarized report on the series

In [65]:
s1.describe()

count      6
unique     6
top       40
freq       1
dtype: int64

In [66]:
s1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: object

# fetch the values

In [71]:
a1 = pd.Series(range(1,10))
a1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [72]:
# fetch first five values
# head default 5 
# Signature: a1.head(n: 'int' = 5) -> 'FrameOrSeries' n
a1.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [73]:
a1.head(2) # its return 1st two entries

0    1
1    2
dtype: int64

# i want fetch last values

In [74]:
a1.tail() # tail also default 5

4    5
5    6
6    7
7    8
8    9
dtype: int64

In [80]:
a1.tail(2) # last 2 entries

7    8
8    9
dtype: int64

# Unique 

In [82]:
a2 = pd.Series([10,12, 21, 12, 10, 45, 41, 21])
a2

0    10
1    12
2    21
3    12
4    10
5    45
6    41
7    21
dtype: int64

In [84]:
a2.unique() # return all unqiue value

array([10, 12, 21, 45, 41], dtype=int64)

In [91]:
a.unique()

array([1, 2, 3, 4, 5, 6])

# Count the unique record

In [92]:
a2.nunique() # get the count of unique record
# its tell you each unique record

5

# count values

In [97]:
a2.value_counts()

10    2
12    2
21    2
41    1
45    1
dtype: int64

# Addition of series

In [99]:
s1 = pd.Series([10, 21, 12])
s1

0    10
1    21
2    12
dtype: int64

In [101]:
s2 = pd.Series([21, 41, 32, 14])
s2

0    21
1    41
2    32
3    14
dtype: int64

In [102]:
s1 + s2 # elementwise addition
# NaN stands for not a number

0    31.0
1    62.0
2    44.0
3     NaN
dtype: float64

In [ ]:
# first series number of enteries must be match of second series  otherwise its put the unmatch index NaN(not a Number)
# s1 is 3 enteries and s2 is 4 enteries  
# index 3 is NaN(elementwise addition)

In [106]:
s2 * s1

0    210.0
1    861.0
2    384.0
3      NaN
dtype: float64

# append two series

In [107]:
s1, s2

(0    10
 1    21
 2    12
 dtype: int64,
 0    21
 1    41
 2    32
 3    14
 dtype: int64)

In [109]:
s1.append(s2) # s2 append in s1

0    10
1    21
2    12
0    21
1    41
2    32
3    14
dtype: int64

In [110]:
s1.append(s2, ignore_index=True) # But the index ordered is change , how to solve this 

0    10
1    21
2    12
3    21
4    41
5    32
6    14
dtype: int64

# Remove 

In [111]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [117]:
# Return item and drops from series. Raise KeyError if not found
s.pop(0) # put inside the index 

1

In [118]:
s

1    2
2    3
3    4
dtype: int64

# N - largest

In [120]:
a1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [121]:
# Return the largest `n` elements.
a1.nlargest() # based on data
# return first 5 largest number default is size is 5, in sorted from

8    9
7    8
6    7
5    6
4    5
dtype: int64

In [122]:
a1.nlargest(3) # keep = first default

8    9
7    8
6    7
dtype: int64

In [127]:
a1.nlargest(3, keep="last")

8    9
7    8
6    7
dtype: int64

In [131]:
a1.nlargest(9,keep="all")

8    9
7    8
6    7
5    6
4    5
3    4
2    3
1    2
0    1
dtype: int64

# n - smallest

In [136]:
 # Return the smallest `n` elements.
a1.nsmallest() # default 5

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [139]:
a1.nsmallest(7, keep="all") 

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [144]:
x = pd.Series([1, 10, 5, 16, 12, 25, 2, 14])
x

0     1
1    10
2     5
3    16
4    12
5    25
6     2
7    14
dtype: int64

In [145]:
x.nsmallest() # defult 5 and sorted

0     1
6     2
2     5
1    10
4    12
dtype: int64

In [147]:
x.nsmallest(keep="last")

0     1
6     2
2     5
1    10
4    12
dtype: int64

In [148]:
x

0     1
1    10
2     5
3    16
4    12
5    25
6     2
7    14
dtype: int64

In [151]:
x.astype("int8") # change dtype

0     1
1    10
2     5
3    16
4    12
5    25
6     2
7    14
dtype: int8

In [152]:
x.astype("category") # change dtype category

0     1
1    10
2     5
3    16
4    12
5    25
6     2
7    14
dtype: category
Categories (8, int64): [1, 2, 5, 10, 12, 14, 16, 25]

In [153]:
x.ndim

1

In [154]:
x.size

8

In [156]:
x.dtype

dtype('int64')

In [157]:
 x

0     1
1    10
2     5
3    16
4    12
5    25
6     2
7    14
dtype: int64

# correlation

In [158]:
s1

0    10
1    21
2    12
dtype: int64

In [159]:
s2

0    21
1    41
2    32
3    14
dtype: int64

In [170]:
s1.corr(s2) # correlational other series 

0.9172139820609867

# Replace values where condition is false

In [179]:
x

0     1
1    10
2     5
3    16
4    12
5    25
6     2
7    14
dtype: int64

In [183]:
x.where(x<5)

0    1.0
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    2.0
7    NaN
dtype: float64

In [185]:
s1

0    10
1    21
2    12
dtype: int64

In [184]:
s1.where(s1<5)

0   NaN
1   NaN
2   NaN
dtype: float64

In [196]:
#x.where(x<5, other="--", inplace=True)
x

0     1
1    --
2     5
3    --
4    --
5    --
6     2
7    --
dtype: object

# Delaing with NaN value

In [205]:
z = pd.Series([np.nan, np.nan, 10, 20, 40, np.nan,32]) # create nan values 
z

0     NaN
1     NaN
2    10.0
3    20.0
4    40.0
5     NaN
6    32.0
dtype: float64

In [207]:
z.isna() # isna (not number is present then true otherwise false)
# bool series will be output

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

# calculate NaN values

In [208]:
z.isna().sum()

3

# fill nan values

In [209]:
z.fillna(0) # fill 0 in nan 

0     0.0
1     0.0
2    10.0
3    20.0
4    40.0
5     0.0
6    32.0
dtype: float64

In [215]:
z.fillna("missing")

0    missing
1    missing
2       10.0
3       20.0
4       40.0
5    missing
6       32.0
dtype: object

In [219]:
z.fillna(2)

0     2.0
1     2.0
2    10.0
3    20.0
4    40.0
5     2.0
6    32.0
dtype: float64

# fill nan value using mean

In [220]:
z

0     NaN
1     NaN
2    10.0
3    20.0
4    40.0
5     NaN
6    32.0
dtype: float64

In [221]:
z.fillna(z.mean())

0    25.5
1    25.5
2    10.0
3    20.0
4    40.0
5    25.5
6    32.0
dtype: float64

In [222]:
z.fillna(z.median()) # Using median 

0    26.0
1    26.0
2    10.0
3    20.0
4    40.0
5    26.0
6    32.0
dtype: float64

In [224]:
# forward filling
z.ffill()

0     NaN
1     NaN
2    10.0
3    20.0
4    40.0
5    40.0
6    32.0
dtype: float64

In [225]:
# backword filling
z.bfill()

0    10.0
1    10.0
2    10.0
3    20.0
4    40.0
5    32.0
6    32.0
dtype: float64

In [226]:
z.max()

40.0

In [227]:
z.min()

10.0

In [228]:
z.mean()

25.5

In [229]:
z.median()

26.0

In [234]:
z.mask(z<11,10)

0     NaN
1     NaN
2    10.0
3    20.0
4    40.0
5     NaN
6    32.0
dtype: float64